export const ADD_ALL_LANES = 'ADD_ALL_LANES';
export const ADD_WINNING_LANES = 'ADD_WINNING_LANES';
export const ADD_OUTBIDDING_LANES = 'ADD_OUTBIDDING_LANES';
export const ADD_WATCHING_LANES = 'ADD_WATCHING_LANES';
export const LOADING_LANES = 'LOADING_LANES';
